### ISSUE TITLE
Pypi upload github action skips

### ISSUE THREAD

**Issue by davidcaron** [jakarto3d/jaklas#14]
This test skips when we have a tag on the master branch (see 0.4.0 tag https://github.com/jakarto3d/jaklas/actions/runs/1147561031):

```
jobs:
  build:
    name: PyPI upload
    if: ${{ github.ref == 'refs/heads/master' }}   <-- here
```
